FROM node:18

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

ARG PORT=3012
ENV PORT=${PORT}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm run prisma:gen

COPY ./apps/apis/users .
COPY tsconfig.json .
COPY tsconfig.build.json .

EXPOSE ${PORT}

CMD ["npm", "run", "start:dev"]


